<?php
namespace TodoCerdo\TodoCerdoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleRepository extends EntityRepository
{
    public function findByPedido($idPedido)
    {
        return $this->getEntityManager()
                ->createQuery('SELECT d FROM TodoCerdoTodoCerdoBundle:Detalle d WHERE d.pedido='.$idPedido.' ORDER BY d.producto ')
                ->getResult();
    }
    

    
    
}
?>
